### 1. Preprocessing

In [4]:
# Load packages
import numpy as np
import pandas as pd
import plotly.express as px

In [5]:
# Display settings
pd.set_option('display.max_columns', None)  
pd.set_option('display.max_rows', None)  
pd.set_option('display.max_colwidth', None)

In [7]:
# Read data
countries = pd.read_excel('Tropical Countries.xlsx')
population = pd.read_csv('Population.csv')
gdp = pd.read_csv('GDP.csv', skiprows=1)
land =  pd.read_csv('Agricultural Land.csv')
precipitation = pd.read_excel('Avg Precipitation.xlsx')

In [8]:
# Create list
countries = countries['Country'].tolist()
dataframes = [population, gdp, land, precipitation]
names = ['population','gdp','land','precipitation']

In [9]:
# Check presence of each country in each dataset
check = pd.DataFrame(columns=['Country'] + names)

for country in countries:
    presence = [country in dataframe['Country'].values for dataframe in dataframes]
    check.loc[len(check)] = [country] + presence

# Display the results
print(check)

                         Country  population    gdp   land  precipitation
0                         Angola        True   True   True           True
1            Antigua and Barbuda        True   True   True           True
2                          Aruba        True   True   True          False
3                       Barbados        True   True   True           True
4                         Belize        True   True   True           True
5                          Benin        True   True   True           True
6         British Virgin Islands        True   True   True          False
7                   Burkina Faso        True   True   True           True
8                        Burundi        True   True   True           True
9                       Cambodia        True   True   True           True
10                      Cameroon        True   True   True           True
11                    Cabo Verde        True   True   True           True
12      Central African Republic        True   True   True           True
13                          Chad        True   True   True           True
14                      Colombia        True   True   True           True
15                       Comoros        True   True   True           True
16                    Costa Rica        True   True   True           True
17                          Cuba        True   True   True           True
18                      Djibouti        True   True   True           True
19                      Dominica        True   True   True           True
20            Dominican Republic        True   True   True           True
21                         Congo        True   True   True          False
22                       Ecuador        True   True   True           True
23                   El Salvador        True   True   True           True
24             Equatorial Guinea        True   True   True           True
25                       Eritrea        True   True   True           True
26                      Ethiopia        True   True   True           True
27                          Fiji        True   True   True           True
28                 French Guiana       False  False   True          False
29                         Gabon        True   True   True           True
30                        Gambia        True   True   True          False
31                         Ghana        True   True   True           True
32                       Grenada        True   True   True           True
33                    Guadeloupe        True  False   True          False
34                     Guatemala        True   True   True           True
35                        Guinea        True   True   True           True
36                 Guinea Bissau       False  False  False          False
37                        Guyana        True   True   True           True
38                         Haiti        True   True   True           True
39                      Honduras        True   True   True           True
40                     Indonesia        True   True   True           True
41                 Côte d’Ivoire       False   True  False          False
42                       Jamaica        True   True   True           True
43                         Kenya        True   True   True           True
44                      Kiribati        True   True   True          False
45        Lao People's Dem. Rep.       False   True  False          False
46                       Liberia        True   True   True           True
47                        Malawi        True   True   True           True
48                      Malaysia        True   True   True           True
49                      Maldives        True   True   True           True
50                          Mali        True   True   True           True
51              Marshall Islands        True   True   True          False
52                    Martinique        True  False   True          False
53                     Mauritius        True   True   True           True
54                    Micronesia       False   True  False          False
55                         Nauru        True   True   True          False
56                     Nicaragua        True   True   True           True
57                         Niger        True   True   True           True
58                       Nigeria        True   True   True           True
59                         Palau        True   True   True          False
60              Papua New Guinea        True   True   True           True
61                          Peru        True   True   True           True
62                   Philippines        True   True   True           True
63        Dem. Rep. of the Congo       False   True  False          False
64                        Rwanda        True   True   True           True
65         Saint Kitts and Nevis        True   True   True          False
66                   Saint Lucia        True   True   True          False
67    Saint Vincent & Grenadines       False   True  False          False
68                         Samoa        True   True   True           True
69         Sao Tome and Principe        True   True   True           True
70                       Senegal        True   True   True           True
71                    Seychelles        True   True   True           True
72                  Sierra Leone        True   True   True           True
73                     Singapore        True   True   True           True
74               Solomon Islands        True   True   True           True
75                       Somalia        True   True   True           True
76                   South Sudan        True   True   True           True
77                     Sri Lanka        True   True   True           True
78                         Sudan        True   True   True           True
79                      Suriname        True   True   True           True
80                      Tanzania       False  False  False           True
81                      Thailand        True   True   True           True
82                   Timor-Leste        True   True   True           True
83                          Togo        True   True   True           True
84                         Tonga        True   True   True          False
85           Trinidad and Tobago        True   True   True           True
86                        Tuvalu        True   True   True          False
87                        Uganda        True   True   True           True
88  United States Virgin Islands        True  False   True          False
89                       Vanuatu        True   True   True           True
90    Venezuela (Boliv. Rep. of)       False   True  False          False
91                      Viet Nam        True   True   True          False
92                         Yemen        True   True   True          False
93                        Zambia        True   True   True           True

In [10]:
# Select countries with complete data
index = check.iloc[:, 1:].all(axis=1)
countries = check[index]['Country'].tolist()
print(countries)

['Angola', 'Antigua and Barbuda', 'Barbados', 'Belize', 'Benin', 'Burkina Faso', 'Burundi', 'Cambodia', 'Cameroon', 'Cabo Verde', 'Central African Republic', 'Chad', 'Colombia', 'Comoros', 'Costa Rica', 'Cuba', 'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Ethiopia', 'Fiji', 'Gabon', 'Ghana', 'Grenada', 'Guatemala', 'Guinea', 'Guyana', 'Haiti', 'Honduras', 'Indonesia', 'Jamaica', 'Kenya', 'Liberia', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Mauritius', 'Nicaragua', 'Niger', 'Nigeria', 'Papua New Guinea', 'Peru', 'Philippines', 'Rwanda', 'Samoa', 'Sao Tome and Principe', 'Senegal', 'Seychelles', 'Sierra Leone', 'Singapore', 'Solomon Islands', 'Somalia', 'South Sudan', 'Sri Lanka', 'Sudan', 'Suriname', 'Thailand', 'Timor-Leste', 'Togo', 'Trinidad and Tobago', 'Uganda', 'Vanuatu', 'Zambia']

In [11]:
# Create a dataframe with all combined data
df = pd.DataFrame({'Country': countries})

# GDP
years = [1995, 2005, 2010, 2015, 2020]
for country in countries:
    for year in years:
        gdp_value = gdp[(gdp['Country'] == country) & (gdp['Year'] == year) & (gdp['Series'] == 'GDP per capita (US dollars)')]['Value']
        column_name = f'gdp_{year}'
        if not gdp_value.empty:
            df.loc[df['Country'] == country, column_name] = gdp_value.values
        else:
            df.loc[df['Country'] == country, column_name] = 'No Data'
df.loc[df['Country']=='South Sudan', 'gdp_1995'] = gdp[(gdp['Country'] == 'Sudan [former]') & (gdp['Year'] == 1995) & (gdp['Series'] == 'GDP per capita (US dollars)')]['Value'].values
df.loc[df['Country']=='Sudan', 'gdp_1995'] = gdp[(gdp['Country'] == 'Sudan [former]') & (gdp['Year'] == 1995) & (gdp['Series'] == 'GDP per capita (US dollars)')]['Value'].values
df.loc[df['Country']=='South Sudan', 'gdp_2005'] = gdp[(gdp['Country'] == 'Sudan [former]') & (gdp['Year'] == 2005) & (gdp['Series'] == 'GDP per capita (US dollars)')]['Value'].values
df.loc[df['Country']=='Sudan', 'gdp_2005'] = gdp[(gdp['Country'] == 'Sudan [former]') & (gdp['Year'] == 2005) & (gdp['Series'] == 'GDP per capita (US dollars)')]['Value'].values

# Population
years = [1995, 2005, 2010, 2015, 2020]
for country in countries:
    for year in years:
        population_value = population[(population['Country'] == country) & (population['Year'] == year)]['Value']
        column_name = f'population_{year}'
        if not population_value.empty:
            df.loc[df['Country'] == country, column_name] = population_value.values
        else:
            df.loc[df['Country'] == country, column_name] = 'No Data'                        
df.loc[df['Country']=='South Sudan', 'population_1995'] = population[(population['Country'] == 'Sudan (former)') & (population['Year'] == 1995)]['Value'].values
df.loc[df['Country']=='Sudan', 'population_1995'] = population[(population['Country'] == 'Sudan (former)') & (population['Year'] == 1995)]['Value'].values
df.loc[df['Country']=='South Sudan', 'population_2005'] = population[(population['Country'] == 'Sudan (former)') & (population['Year'] == 2005)]['Value'].values
df.loc[df['Country']=='Sudan', 'population_2005'] = population[(population['Country'] == 'Sudan (former)') & (population['Year'] == 2005)]['Value'].values
df.loc[df['Country']=='South Sudan', 'population_2010'] = population[(population['Country'] == 'Sudan (former)') & (population['Year'] == 2010)]['Value'].values
df.loc[df['Country']=='Sudan', 'population_2010'] = population[(population['Country'] == 'Sudan (former)') & (population['Year'] == 2010)]['Value'].values
            
# Land
years = [1995, 2005, 2010, 2015, 2020]
for country in countries:
    for year in years:
        land_value = land[(land['Country'] == country) & (land['Year'] == year)]['Value']
        column_name = f'land_{year}'
        if not land_value.empty:
            df.loc[df['Country'] == country, column_name] = land_value.values
        else:
            df.loc[df['Country'] == country, column_name] = 'No Data'  
df.loc[df['Country']=='South Sudan', 'land_1995'] = land[(land['Country'] == 'Sudan (former)') & (land['Year'] == 1995)]['Value'].values
df.loc[df['Country']=='Sudan', 'land_1995'] = land[(land['Country'] == 'Sudan (former)') & (land['Year'] == 1995)]['Value'].values
df.loc[df['Country']=='South Sudan', 'land_2005'] = land[(land['Country'] == 'Sudan (former)') & (land['Year'] == 2005)]['Value'].values
df.loc[df['Country']=='Sudan', 'land_2005'] = land[(land['Country'] == 'Sudan (former)') & (land['Year'] == 2005)]['Value'].values
df.loc[df['Country']=='South Sudan', 'land_2010'] = land[(land['Country'] == 'Sudan (former)') & (land['Year'] == 2010)]['Value'].values
df.loc[df['Country']=='Sudan', 'land_2010'] = land[(land['Country'] == 'Sudan (former)') & (land['Year'] == 2010)]['Value'].values              

# Avg Precipitation
for country in countries:
    precipitation_value = precipitation[(precipitation['Country'] == country)]['2020']
    column_name = 'precipitation_avg'
    if not precipitation_value.empty:
        df.loc[df['Country'] == country, column_name] = precipitation_value.values
    else:
        df.loc[df['Country'] == country, column_name] = 'No Data'

In [12]:
df

,Country,gdp_1995,gdp_2005,gdp_2010,gdp_2015,gdp_2020,population_1995,population_2005,population_2010,population_2015,population_2020,land_1995,land_2005,land_2010,land_2015,land_2020,precipitation_avg
0,Angola,476,"1,902","3,588","4,167","1,896",13912.253,19450.959,23364.185,28127.721,33428.486,44490.0,44183.0,44850.0,45789.0000,45892.0000,"1,010.0"
1,Antigua and Barbuda,"8,407","12,459","13,049","14,286","13,993",68.398,79.869,85.695,89.941,92.664,9.0,9.0,9.0,9.0000,9.0000,"1,030.0"
2,Barbados,"8,637","14,242","16,056","16,525","15,449",262.303,269.477,274.711,278.083,280.693,19.0,16.0,15.0,11.0000,10.0000,"1,422.0"
3,Belize,"2,998","3,916","4,304","4,805","3,988",203.556,280.375,322.106,359.871,394.921,146.0,152.0,157.0,170.0000,180.0000,"1,705.0"
4,Benin,397,602,758,"1,076","1,254",6046.511,8149.419,9445.71,10932.783,12643.123,2520.0,3484.0,3650.0,3950.0000,3950.0000,"1,039.0"
5,Burkina Faso,268,458,647,653,831,10353.263,13876.127,16116.845,18718.019,21522.626,9450.0,10683.0,11242.0,11986.0000,12614.0000,748.0
6,Burundi,167,152,234,277,286,5932.783,7388.874,9126.605,10727.148,12220.227,2037.0,1819.0,1833.0,1941.0000,2076.0000,"1,274.0"
7,Cambodia,311,474,786,"1,163","1,513",10919.528,13246.583,14363.532,15417.523,16396.860,4570.0,5356.0,5403.0,5647.6280,6045.3877,"1,904.0"
8,Cameroon,709,"1,012","1,285","1,326","1,502",13211.647,17275.171,19878.036,23012.646,26491.087,9160.0,9213.0,9700.0,9750.0000,9750.0000,"1,604.0"
9,Cabo Verde,"1,444","2,387","3,378","3,042","3,064",411.382,492.827,521.212,552.166,582.640,70.0,76.0,78.0,79.0000,79.0000,228.0
10,Central African Republic,362,350,488,377,481,3276.706,4208.834,4660.067,4819.333,5343.020,4950.0,4945.0,4907.0,4907.0000,4909.0000,"1,343.0"
11,Chad,234,662,918,828,679,6888.856,10005.012,11894.727,14140.274,16644.701,48450.0,48930.0,49235.0,50237.0000,50338.0000,322.0
12,Colombia,"3,009","3,414","6,337","6,176","5,333",35970.101,42220.94,44816.108,47119.728,50930.662,44513.0,42557.0,42503.0,44784.4000,44052.2780,"3,240.0"
13,Comoros,"1,016","1,287","1,315","1,242","1,421",483.76,592.683,656.024,730.216,806.166,122.0,133.0,133.0,133.0000,133.0000,900.0
14,Costa Rica,"3,264","4,677","8,227","11,643","12,077",3572.856,4315.887,4622.252,4895.242,5123.105,2048.0,1805.0,1819.0,1791.5000,1786.0000,"2,926.0"
15,Cuba,"2,795","3,787","5,730","7,700","9,478",10926.703,11246.114,11290.417,11339.894,11300.698,6684.0,6637.0,6461.2,6240.3000,6401.0000,"1,335.0"
16,Djibouti,808,905,"1,480","2,676","3,465",629.619,830.861,919.199,1006.259,1090.156,1451.6,1701.7,1702.3,1702.8000,1703.9000,220.0
17,Dominica,"3,861","5,160","6,967","7,596","7,038",69.201,68.674,68.755,70.007,71.995,17.0,22.0,25.0,25.0000,25.0000,"2,083.0"
18,Dominican Republic,"2,014","3,903","5,483","6,921","7,268",7869.753,9164.768,9775.755,10405.832,10999.664,2576.0,2417.0,2397.0,2429.0000,2429.0000,"1,410.0"
19,Ecuador,"2,132","3,002","4,634","6,124","5,600",11561.683,13770.012,14989.585,16195.902,17588.595,8108.0,7500.0,7497.7,5789.0000,5420.0000,"2,274.0"
20,El Salvador,"1,585","2,429","2,983","3,706","3,799",5748.195,6037.817,6114.034,6231.066,6292.731,1290.2,1218.6,1229.9,1223.0000,1195.7000,"1,784.0"
21,Equatorial Guinea,433,"11,367","17,272","11,275","7,143",560.74,864.726,1094.524,1346.973,1596.049,102.85,102.98,103.63,104.2800,104.9200,"2,156.0"
22,Eritrea,290,389,501,602,588,2157.22,2831.732,3147.727,3340.006,3555.868,7407.0,7522.0,7592.0,7592.0000,7592.0000,384.0
23,Ethiopia,133,159,300,626,840,57476.536,77469.94,89237.791,102471.895,117190.911,30500.0,33591.0,35683.0,37121.0000,38476.1000,848.0
24,Fiji,"2,571","3,628","3,653","5,391","5,013",792.246,874.923,905.169,917.200,920.422,400.8,342.8,319.1,315.6000,311.6000,"2,592.0"
25,Gabon,"5,087","6,889","8,841","7,379","6,789",1121.964,1458.353,1711.105,2028.517,2292.573,2036.19,2092.295,2117.59,2153.2360,2153.2360,"1,831.0"
26,Ghana,806,"1,044","1,719","1,797","2,206",17438.874,22496.951,25574.719,28870.939,32180.401,13100.0,12119.5796,12400.438,12415.5145,12603.7400,"1,187.0"
27,Grenada,"2,774","6,644","7,258","9,097","9,273",104.06,110.254,114.039,118.980,123.663,11.0,9.0,10.0,8.0000,8.0000,"2,350.0"
28,Guatemala,"1,235","2,045","2,781","3,826","4,332",10363.09,13132.814,14543.121,16001.107,17362.718,4512.0,4562.0,4317.2,4464.0000,4612.0000,"1,996.0"
29,Guinea,724,446,672,769,"1,179",7468.347,9140.114,10270.728,11625.998,13205.153,14024.0,14121.0,14300.0,14545.0000,14635.0000,"1,651.0"
30,Guyana,"1,302","2,651","4,581","5,577","6,956",751.689,759.709,747.932,755.031,797.202,1019.3333,1042.0,1042.0,1042.0000,1042.0000,"2,387.0"
31,Haiti,489,759,"1,187","1,330","1,360",7627.316,9111.9,9842.88,10563.757,11306.801,1590.0,1770.0,1984.0,2068.0000,1790.0000,"1,440.0"
32,Honduras,828,"1,308","1,904","2,302","2,406",5812.832,7564.613,8450.933,9294.505,10121.763,3480.0,3150.0,3268.0,3375.0000,3538.0000,"1,976.0"
33,Indonesia,"1,196","1,345","3,122","3,332","3,870",198140.162,228805.144,244016.173,259091.970,271857.970,42978.0,52130.0,55380.0,57800.0000,64300.0000,"2,702.0"
34,Jamaica,"2,596","4,104","4,704","4,911","4,665",2509.372,2676.863,2733.896,2794.445,2820.436,497.0,467.0,421.3,417.0000,417.0000,"2,051.0"
35,Kenya,530,643,"1,043","1,465","1,879",26878.347,35843.01,41517.895,46851.488,51985.780,27218.0,27002.0,27310.0,27666.0000,27710.0000,630.0
36,Liberia,102,219,332,597,491,2142.422,3266.318,4019.956,4612.329,5087.584,1214.5122,1517.9629,1667.0346,1816.4532,1923.0400,"2,391.0"
37,Malawi,251,290,479,491,615,10112.816,12755.648,14718.422,16938.942,19377.061,4280.0,5180.0,5485.0,5706.0000,5984.0000,"1,181.0"
38,Malaysia,"4,336","5,587","9,041","9,955","10,402",20136.888,25923.536,28717.731,31068.833,33199.993,6966.0,7134.41,7389.3,8569.9700,8571.0000,"2,875.0"
39,Maldives,"2,228","3,640","7,077","9,033","6,924",258.208,307.018,361.575,435.582,514.438,8.0,9.0,6.9,6.4000,6.4000,"1,972.0"
40,Mali,296,489,710,751,856,9921.094,13180.551,15529.181,18112.907,21224.040,35419.0,40392.0,41051.0,41996.0000,42942.0000,282.0
41,Mauritius,"3,786","5,544","8,016","9,284","8,587",1160.207,1258.048,1283.33,1293.153,1297.828,104.0,96.0,91.0,86.0000,86.0000,"2,041.0"
42,Nicaragua,885,"1,158","1,504","2,050","1,905",4721.929,5454.678,5855.734,6298.598,6755.895,4553.0,5250.0,5050.0,5073.0000,5091.0000,"2,280.0"
43,Niger,256,337,464,484,568,9813.918,13855.221,16647.543,20128.124,24333.639,36000.0,42965.0,43982.0,45695.0000,46595.0000,151.0
44,Nigeria,468,"1,268","2,292","2,730","2,085",108187.61,140490.722,160952.853,183995.785,208327.405,64079.0,66256.0,66994.0,67737.0000,68493.0000,"1,150.0"
45,Papua New Guinea,"1,410","1,132","1,949","2,679","2,640",4616.439,6498.818,7583.269,8682.174,9749.640,994.0,1133.0,1267.0,1322.0000,1418.0000,"3,142.0"
46,Peru,"2,196","2,730","5,082","6,229","6,163",24449.055,28147.267,29229.572,30711.863,33304.756,22496.8,23992.8,24794.3,24695.8040,24996.9900,"1,738.0"
47,Philippines,"1,213","1,244","2,217","3,001","3,299",69250.468,86261.25,94636.7,103031.365,112190.977,11015.0,11355.0,12100.0,12527.0000,12659.0000,"2,348.0"
48,Rwanda,211,332,610,750,798,5686.897,9026.299,10309.031,11642.959,13146.362,1550.0,1881.0,1922.0,2007.0000,1958.6000,"1,212.0"
49,Samoa,"1,185","2,486","3,722","4,066","3,890",174.902,188.626,194.672,203.571,214.929,51.0,42.0,41.5,75.6200,49.4100,"2,880.0"
50,Sao Tome and Principe,749,801,"1,095","1,596","2,174",133.077,161.68,182.138,201.124,218.641,28.0,34.0,33.0,37.0000,42.0000,"3,200.0"
51,Senegal,726,"1,016","1,319","1,218","1,458",8632.681,10974.057,12530.121,14356.181,16436.120,8815.0,8776.0,9278.0,9328.0000,9430.0000,686.0
52,Seychelles,"8,011","10,368","10,628","14,503","10,767",74.735,85.883,92.409,99.240,105.530,4.0,4.0,2.4,1.5500,1.5500,"2,330.0"
53,Sierra Leone,274,292,402,592,475,4324.149,5683.334,6436.698,7314.773,8233.970,2810.0,3812.02,3930.38,3949.0000,3949.0000,"2,526.0"
54,Singapore,"24,905","29,962","46,736","55,077","58,114",3543.875,4344.637,5163.59,5650.018,5909.869,1.2,0.76,0.74,0.6600,0.6600,"2,497.0"
55,Solomon Islands,"1,048","1,182","1,710","2,167","2,251",375.189,482.486,540.394,612.660,691.191,73.0,91.0,108.0,116.0000,120.0000,"3,028.0"
56,Somalia,150,222,91,105,118,7210.93,10467.292,12026.649,13763.906,16537.016,44056.0,44126.0,44126.0,44126.0000,44128.0000,282.0
57,South Sudan,440,914,"1,570",581,"1,421",28592.644,37203.231,43454.352,11194.299,10606.227,129644.0,135220.0,137246.2,28392.0500,28250.7000,900.0
58,Sri Lanka,838,"1,429","2,800","3,855","3,768",18177.572,19673.866,20668.557,21336.697,21715.079,2326.0,2510.0,2620.0,2740.0000,2812.0000,"1,712.0"
59,Sudan,440,914,"1,585","2,158","1,415",28592.644,37203.231,43454.352,38171.178,44440.486,129644.0,135220.0,137246.2,111749.8800,112664.8400,250.0
60,Suriname,"1,911","4,391","8,470","9,168","7,023",434.49,516.22,546.08,575.475,607.065,89.0,72.8,78.3,87.0000,80.0000,"2,331.0"
61,Thailand,"2,847","2,894","5,076","5,840","7,189",59424.834,65821.36,68270.489,70294.397,71475.664,21431.0,22360.0,22824.0,22846.0000,23271.8997,"1,622.0"
62,Timor-Leste,493,465,806,"1,333","1,443",819.226,969.313,1088.486,1205.813,1299.995,340.0,333.0,338.0,340.6000,341.4000,"1,500.0"
63,Togo,393,406,534,730,863,4279.566,5711.597,6571.855,7473.229,8442.580,3270.0,3520.0,3665.0,3820.0000,3820.0000,"1,168.0"
64,Trinidad and Tobago,"4,264","12,369","16,714","18,384","15,286",1307.822,1369.075,1410.296,1460.177,1518.147,76.0,54.0,54.0,54.0000,54.0000,"2,200.0"
65,Uganda,350,403,947,766,846,20680.831,27946.588,32341.728,37477.356,44404.611,12122.0,13262.0,14265.0,14415.0000,14415.0000,"1,180.0"
66,Vanuatu,"1,621","1,887","2,967","2,802","2,783",170.612,217.632,245.453,276.438,311.685,165.0,183.0,187.0,187.0000,187.0000,"2,000.0"
67,Zambia,419,703,"1,489","1,314",985,8684.135,11564.87,13792.086,16248.230,18927.715,21653.0,22762.0,23436.0,23739.0000,23839.0000,"1,020.0"

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 68 entries, 0 to 67
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Country            68 non-null     object
 1   gdp_1995           68 non-null     object
 2   gdp_2005           68 non-null     object
 3   gdp_2010           68 non-null     object
 4   gdp_2015           68 non-null     object
 5   gdp_2020           68 non-null     object
 6   population_1995    68 non-null     object
 7   population_2005    68 non-null     object
 8   population_2010    68 non-null     object
 9   population_2015    68 non-null     float64
 10  population_2020    68 non-null     float64
 11  land_1995          68 non-null     object
 12  land_2005          68 non-null     object
 13  land_2010          68 non-null     object
 14  land_2015          68 non-null     float64
 15  land_2020          68 non-null     float64
 16  precipitation_avg  68 non-null     object
dtypes: float64(4), object(13)
memory usage: 9.2+ KB

In [14]:
# Treat as numerical
for column in df.columns:
    if df[column].dtype == 'object':
        df[column] = df[column].astype(str)
        if df[column].str.contains(',').any():
            df[column] = df[column].str.replace(',', '').astype(float)

In [16]:
# Save data
df.to_csv('All.csv',index=False)

### 2. Model Selection

In [17]:
# Read data
df = df.drop('Country',axis=1)

In [18]:
from sklearn.cluster import DBSCAN

dbscan = DBSCAN(eps=0.5, min_samples=5)

labels = dbscan.fit_predict(df)

In [19]:
labels

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
      dtype=int64)